### ISSUE TITLE
Ctrl-C doesn't exit 

### ISSUE THREAD

**Issue by mattstratton** [AlecAivazis/survey#103] opened 2017-10-19 17:44 UTC
I have yet to find any of my implementations that allow Ctrl-C to exit the application.

When it is going through and collecting from a Choice, all that `Ctrl-C` does is re-display the choices.

When I hit a required AskOne, it just skips that particular prompt without taking in a value. For example:

```
func createSpeakerPrompt(city, year string) (err error) {
	var exitCode = true

	for exitCode {
		if city == "" {
			prompt := &survey.Input{
				Message: "Enter the city name:",
			}
			survey.AskOne(prompt, &city, survey.Required)
		}

		if year == "" {
			prompt := &survey.Input{
				Message: "Enter the year:",
			}
			survey.AskOne(prompt, &year, survey.Required)
		}
		speaker.CreateSpeaker("", city, year)
		prompt := &survey.Confirm{
			Message: "Do you want to add another speaker?",
		}
		survey.AskOne(prompt, &exitCode, nil)
	}
	return
}
```

When you go through that, it will prompt you for the city...if you hit ctrl-c, it will then prompt for the year.

**Comment by AlecAivazis** [comment] 2017-10-19 19:03
Hey @mattstratton thanks for reporting this. I was able to reproduce the behavior.

If I run any of the test files and press ctrl-c the test is interrupted. Ctrl-c is handled by returning an error, defined [here](https://github.com/AlecAivazis/survey/blob/89dab5040dc4cf726ba34725f18b0e32ad9608aa/terminal/error.go). I probably need to document this intent more, but my thinking is that series of questions like what you're doing should be done in a single `Ask()`. This unifies the handling of things like interrupts. If I change your example to the following, it works as you originally expected:
```golang
package main

import "github.com/AlecAivazis/survey"

func main() {
	city := ""
	year := "1234"

	var exitCode = true

	for exitCode {
		if city == "" {
			prompt := &survey.Input{
				Message: "Enter the city name:",
			}
			err := survey.AskOne(prompt, &city, survey.Required)
			// handle interrupts
			if err != nil {
				exitCode = false
			}
		}

		if year == "" {
			prompt := &survey.Input{
				Message: "Enter the year:",
			}
			err := survey.AskOne(prompt, &year, survey.Required)
			// handle interrupts
			if err != nil {
				exitCode = false
			}
		}
		prompt := &survey.Confirm{
			Message: "Do you want to add another speaker?",
		}
		err := survey.AskOne(prompt, &exitCode, nil)
		// handle interrupts
		if err != nil {
			exitCode = false
		}
	}
	return

}
```

However, for now, I would suggest doing something slightly different:
```golang
package main

import "github.com/AlecAivazis/survey"

func createSpeakerPrompt(city, year string) error {
	// if we need to keep asking
	for {
		// store the
		answers := struct {
			city string
			year string
			exit bool
		}{city, year}

		// the list of questions to ask
		qs := []*survey.Question{}

		// ask for the city if we dont have one
		if speaker.city == "" {
			qs = append(qs, &survey.Question{
				Name: "city",
				Prompt: &survey.Input{
					Message: "Enter the city name:",
				},
				Validate: survey.Required,
			})
		}

		// ask for the city if we dont have one
		if speaker.year == "" {
			qs = append(qs, &survey.Question{
				Name: "year",
				Prompt: &survey.Input{
					Message: "Enter the year:",
				},
				Validate: survey.Required,
			})
		}

		// make sure to ask to continue
		qs = append(qs, &survey.Question {
			name: "exit",
			Prompt: &survey.Confirm{Message: "Do you want to add another speaker?"}
		})

		// ask the question (and catch interrupts)
		err := survey.Ask(qs, &answers)
		// if there's an interrupt for any question
		if err != nil {
			break
		}

		// create the speaker we need to
		err = speaker.CreateSpeaker("", answers.city, answers.year)
		// if there was an error
		if err != nil {
			return err
		}
		// if we dont want to continue
		if answers.exit {
			break
		}
	}
}
```

Lots of the boilerplate is because there currently isn't a way to modify the questions as part of the API. There's an [issue](https://github.com/AlecAivazis/survey/issues/5) to add this but it hasn't been done yet.

**Comment by mattstratton** [comment] 2017-10-19 19:04
Yeah, I sorta have to take the city and year questions outside of the larger `qs` structure because sometimes they can be passed on the command line (they aren't always asked)

**Comment by AlecAivazis** [comment] 2017-10-19 19:07
Currently, the best way to pull that off is to build up the list of questions depending on the value of `city` and `year`. Hopefully my two examples showed how that would look (i check for `speaker.city` and `speaker.year`). Please let me know if you have any more questions!

**Comment by mattstratton** [comment] 2017-10-19 19:11
Your examples will still work fine with me - in the CreateSpeaker function there are additional questions but it's done in a separate survey.Ask so it's probably fine :)

**Comment by AlecAivazis** [comment] 2017-10-19 19:12
Awesome, i'm going to close this issue. Feel free to open up another if something pops up

**Closed by AlecAivazis** 2017-10-19 19:12 UTC
