### ISSUE TITLE
Survey failed to show output from fmt library

### ISSUE THREAD

**Issue by Nnachevvv** [AlecAivazis/survey#325] opened 2020-12-26 14:49 UTC
**What operating system and terminal are you using?**
Ubuntu 20.04.1 LTS (Focal Fossa)
**An example that showcases the bug.**
```go
package main

import (
	"fmt"

	"github.com/AlecAivazis/survey/v2"
)

// the questions to ask
var qs = []*survey.Question{
	{
		Name:      "name",
		Prompt:    &survey.Input{Message: "What is your name?"},
		Validate:  survey.Required,
		Transform: survey.Title,
	},
}

func main() {

	answers := struct {
		Name string // survey will match the question and field names
	}{}

	for apt := 0; apt < 3; apt++ {
		err := survey.Ask(qs, &answers)
		if err != nil {
			fmt.Println(err)
		}

		fmt.Println("failed to find this combination of name,color")
	}

}


```
**What did you expect to see?**
```

? What is your name? test
failed to find this combination of name,color
? What is your name? testtest
failed to find this combination of name,color
? What is your name? testtest
failed to find this combination of name,color
```

**What did you see instead?**

```
? What is your name? test
? What is your name? testtest
? What is your name? testtest
failed to find this combination of name,color
```

Version of library : github.com/AlecAivazis/survey/v2 v2.2.7

**Comment by mislav** [comment] 2021-09-16 17:30
Duplicate of https://github.com/AlecAivazis/survey/issues/270

The workaround is to construct a new `[]*survey.Question{}` struct for each iteration of the loop instead of reusing the same one.

**Closed by mislav** 2021-09-16 17:30 UTC
Labels: Bug
