### ISSUE TITLE
automated regression testing with expect

### ISSUE THREAD

**Issue by coryb** [AlecAivazis/survey#46] opened 2017-04-26 06:12 UTC
Hey @AlecAivazis, I continue to think about how to best use the files in your `tests` directory.  I think expect is probably the way to go.  

I think the easiest thing to do is use `autoexpect` which will automatically generate an expect script based on watching you interact with a program.  For example I ran it on ask.go like:
```
$ autoexpect -f ask.exp go run ask.go
autoexpect started, file is ask.exp
Asking many.
? What is your name? Larry Bird
? Choose a color: blue
? What is your name? Larry Wall
Answered with Larry Wall.
Asking one with validation.
✘ Sorry, your reply was invalid: Value is required
? What is your name? Larry King
Answered with Larry King.
autoexpect done, file is ask.exp
```
It automatically captured all the input and output for that process and turned it into a script that can be directly executed to recreate that exact sequence.  So if you run it the output will be the same:
```
$ ./ask.exp
spawn go run ask.go
Asking many.
? What is your name? Larry Bird
? Choose a color: blue
? What is your name? Larry Wall
Answered with Larry Wall.
Asking one with validation.
✘ Sorry, your reply was invalid: Value is required
? What is your name? Larry King
Answered with Larry King.
```
The `ask.exp` script that was generated will have all the output captured, even all the CSI codes.

Here is a useful snippet of `ask.exp`:
```
expect -exact "Asking many.\r
^[\[2K^[\[1;92m? ^[\[0m^[\[1;99mWhat is your name? ^[\[0m^[\[37m(Johnny Appleseed) ^[\[0m"
send -- "Larry Bird\r"
expect -exact "Larry Bird\r
^[\[1A^[\[2K^[\[1;92m? ^[\[0m^[\[1;99mWhat is your name? ^[\[0m^[\[36mLarry Bird^[\[0m\r
^[\[2K^[\[1;92m? ^[\[0m^[\[1;99mChoose a color:^[\[0m\r
^[\[1;99m  red^[\[0m\r
^[\[1;99m  blue^[\[0m\r
^[\[1;99m  green^[\[0m\r
^[\[1;36m> yellow^[\[0m\r
^[\[?25l^[\[2K^[\[1F^[\[2K^[\[1F^[\[2K^[\[1F^[\[2K^[\[1F^[\[2K^[\[1F^[\[2K^[\[1;92m? ^[\[0m^[\[1;99mChoose a color:^[\[0m\r
^[\[1;99m  red^[\[0m\r
^[\[1;99m  blue^[\[0m\r
^[\[1;99m  green^[\[0m\r
^[\[1;36m> yellow^[\[0m\r
"
```
Here we can see that I answered `Larry Bird` (the `send`) for the first name prompt, then the tty echo's that name back, then the prompt is rewritten with the name (`Answer`) colored in, followed by the "Choose a color" prompt (twice because Select.OnChange is called automatically with `nil` list on `readline.SetConfig`)

It might be useful if you want to just generate `autoexpect` scripts for each of these tests for the input you have been using to test with.  Then we can just run them in a quick loop to make sure they  all execute without error for a quick and easy regression test.

Not sure what platform, but if you use OSX you can easily install with `brew install expect` (which comes with `autoexpect`).

**Comment by AlecAivazis** [comment] 2017-04-27 01:35
Hmm so i'm not a huge fan of adding such an external dependency, especially since it adds new constraints on the dev flow. Thanks to survey, I try do just over half of my work on a windows machine so I dont forget about "the other side".

I'm curious if we can pull off something similar by providing a `ReadWriter` to the `Stdin` of the readline instance and `terminal` package.

**Comment by AlecAivazis** [comment] 2017-04-27 01:36
Although if this existed on the side of the scripts, so I could still run them by hand and then we just have Travis run the regression tests in its guaranteed Linux environment. That would definitely solve the problem in the short run (assuming the ReadWrite is non-trivial, which it feels like it would be)

**Comment by coryb** [comment] 2017-04-27 02:51
As far as effort goes, I think it would take ~5min to create a regression suite with `autoexpect` which could be run on travis (which now also supports OSX as well as linux).  So to me that has pretty high value with little effort.  For windows that is a port maintained by ActiveState: http://docs.activestate.com/activetcl/8.4/expect4win/ which might help with quasi manual testing.  I could take a stab at creating these tests and hooking them up to travis, and if you decide you want to go in a different direction we can purge these scripts.

**Comment by AlecAivazis** [comment] 2017-04-27 04:46
Alright that sounds like a good plan. looking forward to seeing what you come up with

**Comment by coryb** [comment] 2017-04-27 04:52
Blorgh, I played around with it a bit more and the expect scripts that are generated do not fail cleanly when the output does not match, so this probably wont work as a regression after all.  Off to try something less easy :)

**Comment by AlecAivazis** [comment] 2017-05-11 08:58
I'm closing this since the `autoplay` PR was finally merged

**Closed** 2017-05-11 08:58 UTC
