### ISSUE TITLE
Pressing a key during option selection sometimes re-prints prompt

### ISSUE THREAD

**Issue by sgreene570** [AlecAivazis/survey#268] opened 2020-01-30 18:39 UTC
When selecting from a list of options using the arrow keys, each press of the arrow keys (or any other key from what I can tell) will re-print the prompt question above the choices. Here is a screenshot:

![2020-01-30-133416_649x415_scrot](https://user-images.githubusercontent.com/17414243/73479064-39480300-4365-11ea-84b3-70d327baa6e8.png)

I am using xTerm running bash with the `-norc` flag set. Can provide more details if need be. 
If I press "?" for help, every subsequent key press will also re print the help message, which is especially strange.

System:
xTerm on Debian 10 buster on top of Openbox.
survey v1.8.7
Bash env (trimmed):
```
SHELL=/bin/bash
WINDOWID=41943055
QT_ACCESSIBILITY=1
XTERM_VERSION=XTerm(344)
XTERM_SHELL=/bin/bash
XDG_SEAT=seat0
XDG_SESSION_TYPE=tty
XAUTHORITY=/home/sgreene/.Xauthority
WINDOWPATH=1
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
INVOCATION_ID=500a6237f6d94751a3e6d97ee83f771b
XTERM_LOCALE=en_US.UTF-8
XDG_SESSION_CLASS=user
TERM=xterm
USER=sgreene
DISPLAY=:0
SHLVL=3
XDG_VTNR=1
CLUTTER_PAINT=disable-clipped-redraws:disable-culling
XDG_SESSION_ID=2
XDG_RUNTIME_DIR=/run/user/1000
JOURNAL_STREAM=9:24810
HUSHLOGIN=FALSE
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
_=/usr/bin/env
```

**Comment by matthew119427** [comment] 2020-02-09 02:21
Can reproduce.

**Comment by AlecAivazis** [comment] 2020-02-10 19:18
Hey @sgreene570 and @matthew119427 - thanks for reporting this. This is a duplicate of #101. I'm going to close this to keep things tidy. Feel free to move discussion of the bug there

**Closed by AlecAivazis** 2020-02-10 19:18 UTC

**Comment by sgreene570** [comment] 2020-02-10 19:22
Thanks @AlecAivazis , sorry for the noise :smile:
