### ISSUE TITLE
confirm and input prompts not working on windows

### ISSUE THREAD

**Issue by coryb** [AlecAivazis/survey#52] opened 2017-05-02 19:09 UTC
copying from discussion started in #51.

I ran go run tests\confirm.go and saw:
```
Enter 'yes'
? yes: (y/N) 
             ? yes: Yes
Answered true.
---------------------
Enter 'no'
? yes: (y/N)
             ? yes: No
Answered false.
---------------------
```

Select/Multiselect seems to work, but the recent changes to deal with the `Help` prompt rewriting seems to have broken the input and confirm prompts on windows.

Using `cmd.exe` on Window 10.

**Comment by AlecAivazis** [comment] 2017-05-03 04:39
Just verified this on my windows machine - thanks for reporting this. I'm sure you're looking into it but I'm going to take a look and see if I can spot what's wrong1

**Comment by AlecAivazis** [comment] 2017-05-03 05:00
Btw, part of the issue is the user of `CursorUp`, that's another artifact from go-ansi and probably should be private since `terminal.CursorPreviousLine` is the one I use for reliable results

**Comment by coryb** [comment] 2017-05-03 05:38
Okay, interesting, I didnt look too deep for `CursorUp` vs `CursorPreviousLine`, so that is likely one issues.  Not sure what is up with the non-echoing prompt, esp weird since I explicitly stub out the `RawMode` funcs for Readline when using that in `Input` and `Confirm`, not sure how a no-op can change things.  I have not had time the last few days to look further.  I got a loaner windows laptop today so I hope to be able to play around with it over the next few days.

**Comment by AlecAivazis** [comment] 2017-05-03 07:55
Well I suppose I shouldn't be that surprised but when I tried to boot up my windows machine tonight it crashed with some error that apparently means AVG doesn't like me anymore (not sure if that's even still a used anti-virus haha).

**Comment by coryb** [comment] 2017-05-07 16:55
Hey, making some progress, it took some time for me to get a useful development environment on a windows system.  Basically I am pulling out the pieces of Readline that we need (the MakeRaw and GetConsoleInput).  It should be a lot simpler to follow along with what is actually going on.  I already have `Confirm` and `MultiSelect` working with the replacement.  The work today will be getting `Password` to work which should not be too hard.   The current idea is to have an `InputReader` struct with funcs to `ReadRune`, `ReadLine`, `EnableEchoMode`, `EnableLineMode`, and `RestoreModes` (to reset the tty modes).  Planning on putting that code in the `terminal` package we have.    Hopefully will have the code ready for a PR tonight or tomorrow.

**Comment by AlecAivazis** [comment] 2017-05-11 07:08
Closing this since we finally got that PR in - thanks again @coryb!

**Closed by AlecAivazis** 2017-05-11 07:08 UTC
