### ISSUE TITLE
[Discussion] Support for display name in Select prompts

### ISSUE THREAD

**Issue by filabrazilska** [AlecAivazis/survey#153] opened 2018-10-08 16:45 UTC
Hi,
we would like to have a Select prompt that would use different sets of strings for display and for reporting the selected value, something like this:
```
type Option struct {
    name string
    displayName string 
}
```
and then the following change would have to be done to the definition of `Select` type:
```
type Select struct {
    ...
    options []Option
    ...
}
```

This way it would be possible to use the `displayName` values when displaying the select (and for filtering) while the `name` value of the selected option will be the result of the selection process.
Sadly this change would break backwards compatibility and didn't find a way create an Option object from the provided string transparently to the users of the library. 
Another option that comes to my mind in order to support his behaviour would have been to create another type (eg. `TypedSelect`) to use with `Ask()` but that seems to have substantial overhead.

Please let me know what do you think.

**Comment by AlecAivazis** [comment] 2018-10-08 17:03
Hey @filabrazilska  - thanks for submitting this issue. 

In general, I think your usecase makes a lot of sense. This is probably one of the most requested features of `survey`. While the name of the issue is a bit misleading, there has been a lot of discussion on #105 to figure out the best way to support this. I'm going to close this issue sine it is a duplicate, but I will rename that issue with your title as its much better 😄

**Closed by AlecAivazis** 2018-10-08 17:03 UTC
