### ISSUE TITLE
Default value for Input does not show after pressing "enter"

### ISSUE THREAD

**Issue by jandersongo** [AlecAivazis/survey#398] opened 2021-12-29 22:55 UTC
<img width="301" alt="Screen Shot 2021-12-29 at 5 50 09 PM" src="https://user-images.githubusercontent.com/66972585/147709001-7da5ce79-48f2-435b-a779-d7f799945e21.png">
<img width="297" alt="Screen Shot 2021-12-29 at 5 50 30 PM" src="https://user-images.githubusercontent.com/66972585/147709004-a2230712-e2a3-4f28-a430-78d0706f581f.png">

The default value for survey.Input does not show after pressing "enter"

[1st line in screenshot] The survey.Confirm correctly shows "Yes" in cyan. 
[3rd line in screenshot] The survey.Select correctly shows the selected value in cyan. 
[2nd line in screenshot] I would expect to see the "default_name_here" show up in cyan as the input answer. 

Using MacOS & zsh

**Comment by MehrunesSky** [comment] 2022-05-02 17:07
I test on MacOS and the default value appair after pressing "enter".

Can you tell me if the problem is still present?

**Comment by mislav** [comment] 2022-05-12 13:53
@jandersongo I also could not reproduce with latest Survey and it seems that the default value is properly rendered in cyan in the final line after choosing the default input value. I will close this, but if you manage to make a minimal reproduction case, please share it!

**Closed by mislav** 2022-05-12 13:53 UTC
Labels: Bug
