### ISSUE TITLE
Last line in prompt becomes invisible when a character is typed and then deleted on a previous line

### ISSUE THREAD

**Issue by pokir** [AlecAivazis/survey#437] opened 2022-08-03 13:51 UTC
**What operating system and terminal are you using?**

MacOS 12.4; alacritty (but bug is reproducible in any terminal)

**An example that showcases the bug.**

This is a bug found in GitHub's CLI that uses the `survey` library.
See [this issue in GitHub's CLI](https://github.com/cli/cli/issues/6015#issuecomment-1203709949).

1. Open new terminal window in a git repo
2. Press enter many times until the terminal scrolls down
3. Run `gh issue create`
4. Type text in the `Title` prompt until it wraps to a new line at least once
5. Move the cursor to a previous line before the line wrap
6. Type a character and delete it

<img width="531" alt="Capture d’écran 2022-07-31 à 17 03 11" src="https://user-images.githubusercontent.com/80112484/182032598-4292fd06-65a7-48a2-8b35-a8af75795fed.png">

<img width="532" alt="Capture d’écran 2022-07-31 à 17 03 24" src="https://user-images.githubusercontent.com/80112484/182032606-09ee68de-ced9-43fd-a2cb-f89e9352cab0.png">

<img width="532" alt="Capture d’écran 2022-07-31 à 17 03 39" src="https://user-images.githubusercontent.com/80112484/182032610-dd57037d-5cb1-4adc-bad2-4b9ea0c6d2b9.png">

**What did you expect to see?**

Text on the last line

**What did you see instead?**

No text on the last line

**Comment by pokir** [comment] 2022-08-11 18:34
This can also be done with `go run examples/simple.go` (in the repo) instead of using `gh`.

**Comment by AlecAivazis** [comment] 2022-09-22 21:48
Mind checking if this is still a problem now that #445 has been merged? I'm unable to reproduce it on the lastest master

**Comment by AlecAivazis** [comment] 2022-10-24 16:45
I'm going to close this since its gone a bit stale and I can't reproduce it.

**Closed by AlecAivazis** 2022-10-24 16:45 UTC
Labels: Bug
