### ISSUE TITLE
The question duplicates when terminal overflows

### ISSUE THREAD

**Issue by ghost** [AlecAivazis/survey#101] opened 2017-10-15 10:07 UTC

**Comment by AlecAivazis** [comment] 2017-10-17 07:17
Gah! Sorry to hear this, i'll try to fix it ASAP - do you by chance have access to a linux machine and could see if it's affecting you there too? I'm pretty sure I verified overflow behavior on a posix terminal but there might be something special with your question or prompt.

**Comment by Frodgy** [comment] 2017-10-18 20:47
@AlecAivazis, I don't have an access even to Linux VM, but I assume, this bug doesn't affect only password asking. Same "overflowing" behaviour with select option.

**Comment by AlecAivazis** [comment] 2017-10-20 03:42
Okay no worries. Since I'm currently on a windows machine I figured I leave a note to my future self that I was able to reproduce this with the `ask` test and a very thin console. It only duplicated on clean-up.

<img width="274" alt="capture" src="https://user-images.githubusercontent.com/916317/31804401-f8464c96-b50d-11e7-8f8f-1a4a83a87b63.PNG">

**Comment by geocine** [comment] 2018-03-25 13:42
related issue #136 on mac

**Comment by AlecAivazis** [comment] 2018-03-26 16:14
Just verified that this also affects OSX terminals

**Comment by DeepAnchor** [comment] 2018-07-27 02:47
Running into this problem now on macOS! I had a look through the source code but can't find anything obvious that could be causing this.

The funny thing is that the same thing also happens with another popular CLI prompt [(promptui)](https://github.com/manifoldco/promptui). At first I thought it might be related to promptui's dependency on [readline](https://github.com/chzyer/readline) but apparently that's not it.

Any hunches as to what could be causing this?

**Comment by zanven42** [comment] 2018-09-13 08:16
I resolved this issue by disabling line wrap before calling into the package to ask the questions. 

`		// make terminal not line wrap
		fmt.Printf("\x1b[?7l")
		// defer restoring line wrap
		defer fmt.Printf("\x1b[?7h")
`

**Comment by palash25** [comment] 2018-12-18 15:03
> do you by chance have access to a linux machine and could see if it's affecting you there too? 

Hi there we are currently using this package for implementing a command in our [project](https://github.com/appbaseio/abc) and I experienced the same [issue](https://github.com/appbaseio/abc/pull/121#issuecomment-448219383) on my machine (OS: Ubuntu 16.04, shell: zsh). 

Please let me know when its fixed :smile:

**Comment by isacikgoz** [comment] 2018-12-21 13:11
issue confirmed  (OS: Ubuntu 18.04.1, shell: zsh). Another workaround may be get terminal column size then insert new lines at that index before rendering text.

**Comment by metacosm** [comment] 2019-01-03 13:40
The issue happens because https://github.com/AlecAivazis/survey/blob/master/core/renderer.go#L77 doesn't take wrapping into account (i.e. when the terminal wraps, it adds extra `\n` that were not present in the initial rendered template) resulting in `resetPrompt` erasing only (original number of lines - number of wrapped lines) lines.

**Comment by metacosm** [comment] 2019-01-03 13:49
Perhaps it would be worth using a terminal emulation library to deal with this issue, though of course that would mean adding another dependency…

**Comment by metacosm** [comment] 2019-01-14 10:35
@AlecAivazis any idea on when this issue could be fixed?

**Comment by jorng** [comment] 2019-03-05 22:02
This is biting me too. Any ideas on how to fix?

**Comment by metacosm** [comment] 2019-03-06 08:40
I had taken a quick look but there was no obvious solution with the current implementation as it doesn't have access to the text being currently displayed (iirc). As a workaround, I wrap lines "manually" before handing text that I know might wrap to survey… Not ideal.

**Comment by isacikgoz** [comment] 2019-03-06 09:09
I think the most suitable solution would be:

1. Implementing a watchdog for terminal size, as this issue also happens when terminal resize.
2. Send an event to renderer/writer to re-draw the prompt if line lengths exceed terminal width.
3. Re-draw and add "\n" to avoid unwanted glitches.

I use a similar mechanism on a project but it's not public at the moment. So, I can't link the code here.  Although I don't use survey, things work similar.

**Comment by cgchoffman** [comment] 2019-03-26 20:16
Seeing this in Linux terminals as well, not just OSX.

**Comment by PrMinisterGR** [comment] 2019-08-22 08:54
I managed to "fix" this by disabling the "Message" part of the prompt.

**Comment by sgreene570** [comment] 2020-02-10 19:28
I also noticed that if you press "?" for a help message (when that feature is being used) and then press a different key the help message will be re-printed instead of the original message (presumably since it's the last thing that was displayed?). Not sure if that helps with debugging.

**Comment by bcatubig** [comment] 2020-04-11 23:15
![image](https://user-images.githubusercontent.com/1383904/79056866-685dd900-7c20-11ea-9237-6a5b31ba89c6.png)

seeing this in Konsole as well. Prompt reprints instead of refreshing terminal. 

Behavior is not present in Gnome Terminal or Xterm.

**Comment by AlecAivazis** [comment] 2020-07-08 05:46
We can finally close this!! :tada::tada::tada: 

Thank you so much @coryb and @Zalgo2462! Like i said, this has been a problem for a very very long time. Thank you for seeing this through

**Closed by AlecAivazis** 2020-07-08 05:46 UTC
Labels: Bug, Help Wanted
